name: css_methods_python_env
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.11.1
  - feedparser=6.0.8
  - gensim=4.1.2
  - ipywidgets=7.6.5
  - matplotlib=3.5.2
  - networkx=2.8.4
  - numpy=1.21.5
  - pandas=1.4.4
  - pip=22.2.2
  - python=3.9.13
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.9.1
  - seaborn=0.11.2
  - selenium=3.141.0
  - spacy=3.3.1
  - sqlalchemy=1.4.39
  - pip:
    - powerlaw==1.5
